[package]
name = "zkrss"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { path = "./aztec-packages/noir-projects/aztec-nr/aztec" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
